### ISSUE TITLE
과제30번

### ISSUE THREAD

**Issue by kim-do-kyun** [1ocalh0st/QnA#2]
```c
#include <stdio.h>

int main()
{
	double a, b;
	
	while (scanf("%lf %lf", &a, &b) == 2)
	{
		printf("%.3lf", (a-b)/(a*b));
		printf("\n");
	}
	return 0;
}

```
에서 수치형이 아닌것이 입력될때 까지라고 했는데 while (scanf("%lf %lf", &a, &b) == 2) 이부분이 왜 이렇게 되나용

**Comment by gitksh** [comment]
```
scanf("%lf %lf", &a, &b) == 2
```

이는 알맞은 값이 2개 입력됬는지 확인하는 것입니다.
scanf는 값을 입력받게 되면 몇개의 값이 제대로 입력됬는지 정수로 반환하게 됩니다.
이 반환값으로 scanf에 값이 제대로 입력됬는지 확인하게 됩니다.

```
while (scanf("%lf %lf", &a, &b) == 2)
```

즉 이 부분은 scanf에 실수형의 값이 2개가 입력된다면 while문을 계속한다는 의미입니다.
